### ISSUE TITLE
Odometry?

### ISSUE THREAD

**Issue by AlphaRant9** [Waterloo-Robotics/ChargedUp5837#5]
At least get an idea of porting the odometry code over to the FRC bot, with a note that strafing can be removed as well as changing the motors from 4 separate to the two motor control groups

**Comment by ghost** [comment]
Installation will hopefully happen this week. Austin was working on it. Could poke him to get it done

**Comment by AlphaRant9** [comment]
Cool, I was moreso looking into copy/pasting the stuff over
